---
kind: Template
apiVersion: v1
metadata:
  name: golang-ex
  annotations:
    description: An example Beego (http://beego.me/) application written in Golang
    tags: quickstart,golang
    iconClass: icon-go-gopher
labels:
  template: golang-ex
  app: golang-ex
objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: golang-ex
    annotations:
      description: Exposes and load balances the application pods
  spec:
    ports:
    - name: web
      port: 8080
      targetPort: 8080
    selector:
      name: golang-ex
- kind: Route
  apiVersion: v1
  metadata:
    name: golang-ex
  spec:
    host: "${APPLICATION_DOMAIN}"
    to:
      kind: Service
      name: golang-ex
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: golang-ex
    annotations:
      description: Keeps track of changes in the application image
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: golang-ex
    annotations:
      description: Defines how to build the application
  spec:
    source:
      type: Git
      git:
        uri: "${SOURCE_REPOSITORY_URL}"
        ref: "${SOURCE_REPOSITORY_REF}"
      contextDir: "${CONTEXT_DIR}"
    strategy:
      type: Docker
    output:
      to:
        kind: ImageStreamTag
        name: golang-ex:latest
    triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secret: "${GITHUB_WEBHOOK_SECRET}"
    postCommit:
      script: go test -v ./...
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: golang-ex
    annotations:
      description: Defines how to deploy the application server
  spec:
    strategy:
      type: Recreate
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - golang-ex
        from:
          kind: ImageStreamTag
          name: golang-ex:latest
    - type: ConfigChange
    replicas: 1
    selector:
      name: golang-ex
    template:
      metadata:
        name: golang-ex
        labels:
          name: golang-ex
      spec:
        containers:
        - name: golang-ex
          image: golang-ex
          ports:
          - containerPort: 8080
parameters:
- name: SOURCE_REPOSITORY_URL
  description: The URL of the repository with your application source code
  value: https://github.com/openshift/golang-ex.git
- name: SOURCE_REPOSITORY_REF
  description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default branch
- name: CONTEXT_DIR
  description: Set this to the relative path to your project if it is not in the root
    of your repository
- name: APPLICATION_DOMAIN
  description: The exposed hostname that will route to the Beego service
  value: golang-ex.openshiftapps.com
- name: GITHUB_WEBHOOK_SECRET
  description: Github trigger secret.  A difficult to guess string encoded as part
    of the webhook URL.  Not encrypted.
  generate: expression
  from: "[a-zA-Z0-9]{40}"
